import { useBlockProps, InnerBlocks } from '@wordpress/block-editor';

export default function save({ attributes }) {
  const { sectionHeading } = attributes;
  const blockProps = useBlockProps.save();

  return (
    <section {...blockProps} className="section_faq-main wp-block-webdune-faq-with-toc">
      <div className="padding-global z-index-1">
        <div className="w-layout-blockcontainer container-large w-container">
          <div className="faq-grid">
            {/* Table of Contents Sidebar */}
            <div className="faq-column">
              <div className="faq_category-sidebar">
                <div className="heading-style-h4">{sectionHeading}</div>
                <div className="faq_category-links" data-faq-toc>
                  {/* ToC links will be generated by view.js */}
                </div>
              </div>
            </div>

            {/* FAQ Categories */}
            <div className="faq-column">
              <div className="faq-sections_list">
                <InnerBlocks.Content />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

